name: easyeditor
version: '1.5.2c'
summary: Easy Markdown Editor
description: |
  Easyeditor is an easy markdown editor that allows you to write Markdown (MD) 
  and preview it in real-time. You can save, load .md files, load Git repo 
  and stage, commit, push and export to HTML, TXT, PDF & SSTP Encryption, This 
  application uses classic confinement because it's a Tauri-based application 
  requiring WebKitGTK 4.1 with full system access for file operations.

grade: stable
confinement: classic
icon: snap/gui/easyeditor.png
base: core24

title: Easyedit
license: MIT
contact: https://github.com/gcclinux/easyeditor/discussions
website: https://easyeditor.co.uk
source-code: https://github.com/gcclinux/easyeditor
issues: https://github.com/gcclinux/easyeditor/issues
donation: https://github.com/sponsors/gcclinux

platforms:
  amd64:

apps:
  easyeditor:
    command: bin/easyeditor
    desktop: snap/gui/easyeditor.desktop

parts:
  easyeditor:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp src-tauri/target/release/easyeditor $SNAPCRAFT_PART_INSTALL/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/easyeditor
      mkdir -p $SNAPCRAFT_PART_INSTALL/snap/gui
      cp snap/gui/easyeditor.desktop $SNAPCRAFT_PART_INSTALL/snap/gui/
      cp snap/gui/easyeditor.png $SNAPCRAFT_PART_INSTALL/snap/gui/
