name: easyedit
version: '1.5.2'
summary: Easy Markdown Editor
description: |
  EasyEdit is an easy markdown editor that allows you to write Markdown (MD) 
  and preview it in real-time. You can save, load .md files, load Git repo 
  and stage, commit, push and export to HTML, TXT, PDF & SSTP Encryption.

grade: stable
confinement: classic
icon: snap/gui/easyedit.png
base: core24

title: Easyedit
license: MIT
contact: https://github.com/gcclinux/easyedit/discussions
website: https://gcclinux.github.io/EasyEdit/
source-code: https://github.com/gcclinux/easyedit
issues: https://github.com/gcclinux/easyedit/issues
donation: https://github.com/sponsors/gcclinux

platforms:
  amd64:

apps:
  easyedit:
    command: bin/easyedit
    desktop: snap/gui/easyedit.desktop

parts:
  easyedit:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp src-tauri/target/release/easyedit $SNAPCRAFT_PART_INSTALL/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/easyedit
